### ISSUE TITLE
buttons disappearing

### ISSUE THREAD

**Issue by lookfirst** [Matesign/material-wizard#1]
This is pretty cool, but the next/prev buttons appearing / disappearing is really confusing. At least in my browser (latest chrome) on the plunkr, it takes a fraction of a second for the button to update. Maybe it would be better to just enable / disable them?

**Comment by afrad** [comment]
Enabling/disabling doesn't really show any visual changes to the buttons. Only the mouse pointer changes. But I agree it is a little confusing. Maybe offering both options?

**Comment by afrad** [comment]
Added chevrons-always-visible attribute, set it to "true" if you want disable/enable the chevrons instead of hide/show them.

**Comment by lookfirst** [comment]
Plunkr seems broken? http://take.ms/jOaG5

**Comment by afrad** [comment]
Thank you. Fixed.
